name: task_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^5.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.3
  smooth_corner: ^1.1.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

